connexus/accounts/urls.py
from django.urls import path, include, reverse
from django.views.generic import TemplateView, RedirectView

from .views import StudentRegistrationView, logout_view, StudentLoginView

app_name = 'accounts'
urlpatterns = [
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path(
        'register/',
        StudentRegistrationView.as_view(),
        name='register'
    ),
    path('login/', StudentLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

connexus/connexus/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'connexus'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
]

connexus/home/urls.py
from django.urls import path, include, reverse
from django.views.generic import TemplateView, RedirectView

from .views import home_page_view

app_name = 'home'
urlpatterns = [
    path('', home_page_view, name='homepage'),
]

connexus/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings


from .managers import UserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    # email and password are required
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active


class StudentInfo(models.Model):
    CHALLENGERS = 'C'
    PIONEERS = 'P'
    EXPLORERS = 'E'
    VOYAGERS = 'V'

    HOUSE_CHOICES = (
        (CHALLENGERS, 'Challengers'),
        (PIONEERS, 'Pioneers'),
        (EXPLORERS, 'Explorers'),
        (VOYAGERS, 'Voyagers')
    )

    CLASS_CHOICES = list(zip(
        list(range(1, 13)), list(map(str, range(1, 13)))
    ))

    SECTIONS = ['A', 'B', 'C', 'D']

    SECTION_CHOICES = list(zip(SECTIONS, SECTIONS))

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )
    admission_number = models.IntegerField(null=True)
    house = models.CharField(max_length=1, choices=HOUSE_CHOICES)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    grade = models.IntegerField(choices=CLASS_CHOICES)
    section = models.CharField(max_length=1, choices=SECTION_CHOICES)

    def __str__(self):
        return f'{self.first_name} {self.last_name[0]}'

    class Meta:
        ordering = ['grade', 'section']
        verbose_name = 'Student info'
        verbose_name_plural = 'Student info'

connexus/blog/models.py
from django.db import models

# Create your models here.

connexus/home/models.py
from django.db import models

# Create your models here.

connexus/accounts/forms.py
# accounts.forms.py
from django import forms

from .models import User
from .admin import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(
        label='email',
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email',
            }
        ),
    )

    password1 = forms.CharField(
        label='password1',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
            }
        )
    )

    password2 = forms.CharField(
        label='password1',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirm Password',
            }
        )
    )

    icons = {
        'password1': 'ni ni-lock-circle-open',
        'password2': 'ni ni-lock-circle-open',
        'email': 'ni ni-email-83'
    }


class UserInfoRegistrationForm(forms.Form):
    admission_number = forms.IntegerField(
        label='admission_number',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Admssion number'
            }
        )
    )

    icons = {
        'admission_number': 'ni ni-lock-circle-open'
    }


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        label='email',
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email',
            }
        ),
    )
    password = forms.CharField(
        label='password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
            }
        )
    )

    icons = {
        'password': 'ni ni-lock-circle-open',
        'email': 'ni ni-email-83'
    }

connexus/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.views.generic import RedirectView
from django.urls import reverse_lazy, reverse

from .forms import UserRegistrationForm, UserLoginForm, UserInfoRegistrationForm
from .models import StudentInfo


def logout_view(request):
    logout(request)
    return redirect(reverse('accounts:home'))


class StudentLoginView(View):
    template_name = 'form.html'
    form_class = UserLoginForm
    message = 'Sign in with'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'message': self.message})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
            else:
                form.add_error('email', 'Wrong email or/and password')
                return render(request, self.template_name, {'form': form, 'message': self.message})
            return redirect('accounts:home')

        return render(request, self.template_name, {'form': forms, 'message': self.message})


class StudentRegistrationView(View):
    template_name = 'form.html'
    form_class = UserRegistrationForm
    second_form_class = UserInfoRegistrationForm
    message = 'Register'

    def get(self, request, *args, **kwargs):
        user_form = self.form_class()
        info_form = self.second_form_class()
        return render(request, self.template_name, {'form': user_form, 'form2': info_form, 'message': self.message})

    def post(self, request, *args, **kwargs):
        user_form = self.form_class(request.POST)
        info_form = self.second_form_class(request.POST)
        if user_form.is_valid() and info_form.is_valid():
            no = info_form.cleaned_data['admission_number']

            # check if this admission number is exists or not
            if not StudentInfo.objects.filter(admission_number=no):
                # This admssion number doesn't exist
                info_form.add_error(
                    'admission_number', 'No such admission number exists.'
                )
                return render(request, self.template_name, {'form': user_form,  'message': self.message})

            # check if admission numberhas been registered or not
            try:
                boi = StudentInfo.objects.get(
                    admission_number=no, user__isnull=True)
                user = user_form.save()
                boi.user = user
                boi.save()
                login(request, user)
                return redirect('accounts:home')
            except:
                info_form.add_error(
                    'admission_number', f'{no} is already a registered account. Have you used your own admission number?'
                )
                return render(request, self.template_name, {'form': user_form, 'form2': info_form, 'message': self.message})

        return render(request, self.template_name, {'form': user_form, 'form2': info_form, 'message': self.message})

connexus/blog/views.py
from django.shortcuts import render

# Create your views here.

connexus/home/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required(login_url=reverse_lazy('accounts:login'))
def home_page_view(request):
    return render(request, 'home\homepage.html')

connexus/accounts/templates/form.html
{% extends 'form_base.html' %}
{% load static %}
{% load dict_access %}
{% load widget_tweaks %}

{% block content %}
<div class="container pt-lg-md">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <div class="card bg-secondary shadow border-0">
                <div class="card-body px-lg-5 py-lg-5">
                    <div class="text-muted text-center mb-3">
                        <small>{{ message }}</small>
                    </div>
                    <form role="form" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="{{ form.icons|hash:field.label }}"></i></span>
                                </div>
                                {% render_field field class+='form-control form-control-alternative'%}
                            </div>
                        </div>
                        {% endfor %}

                        {% if form2 %}
                        {% for field in form2 %}
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="{{ form2.icons|hash:field.label }}"></i></span>
                                </div>
                                {% render_field field class+='form-control form-control-alternative'%}
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary my-4">Sign in</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-6">
                    <a href="#" class="text-light">
                        <small>Forgot password?</small>
                    </a>
                </div>
                <div class="col-6 text-right">
                    <a href="#" class="text-light">
                        <small>Create new account</small>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    {% if form.errors or form2.errors%}
    <div class="alert alert-warning alert-dismissible fade show" role="alert" style="position: fixed; z-index: 100; bottom : 2vh; left: 5%; right: 5%;">
        {% if form.non_field_errors %}
        {% for error in field.non_field_errors %}
        <span class="alert-inner--icon"><i class="fa fa-exclamation-circle"></i></span>
        <span class="alert-inner--text"><strong>{{error}}</strong></span>
        <br/>
        {% endfor %}
        {% endif %}
        
        {% for field in form %}
        {% if field.errors %}
        {% for error in field.errors %}
        <span class="alert-inner--icon"><i class="fa fa-exclamation-circle"></i></span>
        <span class="alert-inner--text"><strong>{{error}}</strong></span>
        <br/>
        {% endfor %}
        {% endif %}
        {% endfor %}

        {% if form2 %}
        {% if form2.non_field_errors %}
        {% for error in field.non_field_errors %}
        <span class="alert-inner--icon"><i class="fa fa-exclamation-circle"></i></span>
        <span class="alert-inner--text"><strong>{{error}}</strong></span>
        <br/>
        {% endfor %}
        {% endif %}
        
        {% for field in form2 %}
        {% if field.errors %}
        {% for error in field.errors %}
        <span class="alert-inner--icon"><i class="fa fa-exclamation-circle"></i></span>
        <span class="alert-inner--text"><strong>{{error}}</strong></span>
        <br/>
        {% endfor %}
        {% endif %}
        {% endfor %}
        {% endif %}
        
        
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% if form2 %}
    
    {% endif %}
</div>
{% endblock content %}

connexus/accounts/templates/form_base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Design System for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>Connexus</title>
  <!-- Favicon -->
  <link href="{% static 'assets/img/brand/favicon.png' %}" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="{% static '/assets/css/argon.css'%}" rel="stylesheet">
  <!-- Docs CSS -->
  <link type="text/css" href="{% static '/assets/css/docs.min.css' %}" rel="stylesheet">
</head>

<body>
  <header class="header-global">
    <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light">
      <div class="container">
        <a class="navbar-brand mr-lg-5" href="../index.html">
          <img src="{% static '/assets/img/brand/white.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar_global">
          <div class="navbar-collapse-header">
            <div class="row">
              <div class="col-6 collapse-brand">
                <a href="../index.html">
                  <img src="{% static '/assets/img/brand/blue.png' %}">
                </a>
              </div>
              <div class="col-6 collapse-close">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global"
                  aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                  <span></span>
                  <span></span>
                </button>
              </div>
            </div>
          </div>
          <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">
                <i class="ni ni-ui-04 d-lg-none"></i>
                <span class="nav-link-inner--text">Components</span>
              </a>
              <div class="dropdown-menu dropdown-menu-xl">
                <div class="dropdown-menu-inner">
                  <a href="https://demos.creative-tim.com/argon-design-system/docs/getting-started/overview.html" class="media d-flex align-items-center">
                    <div class="icon icon-shape bg-gradient-primary rounded-circle text-white">
                      <i class="ni ni-spaceship"></i>
                    </div>
                    <div class="media-body ml-3">
                      <h6 class="heading text-primary mb-md-1">Getting started</h6>
                      <p class="description d-none d-md-inline-block mb-0">Get started with Bootstrap, the world's most
                        popular framework for building responsive sites.</p>
                    </div>
                  </a>
                  <a href="https://demos.creative-tim.com/argon-design-system/docs/components/alerts.html" class="media d-flex align-items-center">
                    <div class="icon icon-shape bg-gradient-warning rounded-circle text-white">
                      <i class="ni ni-ui-04"></i>
                    </div>
                    <div class="media-body ml-3">
                      <h5 class="heading text-warning mb-md-1">Components</h5>
                      <p class="description d-none d-md-inline-block mb-0">Learn how to use Argon compiling Scss,
                        change brand colors and more.</p>
                    </div>
                  </a>
                </div>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">
                <i class="ni ni-collection d-lg-none"></i>
                <span class="nav-link-inner--text">Examples</span>
              </a>
              <div class="dropdown-menu">
                <a href="../examples/landing.html" class="dropdown-item">Landing</a>
                <a href="../examples/profile.html" class="dropdown-item">Profile</a>
                <a href="../examples/login.html" class="dropdown-item">Login</a>
                <a href="../examples/register.html" class="dropdown-item">Register</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <section class="section section-shaped section-lg my-0">
      <div class="shape shape-style-1 bg-gradient-default">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      {% block content %}
      {% endblock %}
    </section>
  </main>
  <footer class="footer">
    <div class="container">
      <div class="row row-grid align-items-center mb-5">
        <div class="col-lg-6">
          <h3 class="text-primary font-weight-light mb-2">Thank you for supporting us!</h3>
          <h4 class="mb-0 font-weight-light">Let's get in touch on any of these platforms.</h4>
        </div>
        <div class="col-lg-6 text-lg-center btn-wrapper">
          <a target="_blank" href="https://twitter.com/creativetim" class="btn btn-neutral btn-icon-only btn-twitter btn-round btn-lg"
            data-toggle="tooltip" data-original-title="Follow us">
            <i class="fa fa-twitter"></i>
          </a>
          <a target="_blank" href="https://www.facebook.com/creativetim" class="btn btn-neutral btn-icon-only btn-facebook btn-round btn-lg"
            data-toggle="tooltip" data-original-title="Like us">
            <i class="fa fa-facebook-square"></i>
          </a>
          <a target="_blank" href="https://dribbble.com/creativetim" class="btn btn-neutral btn-icon-only btn-dribbble btn-lg btn-round"
            data-toggle="tooltip" data-original-title="Follow us">
            <i class="fa fa-dribbble"></i>
          </a>
          <a target="_blank" href="https://github.com/creativetimofficial" class="btn btn-neutral btn-icon-only btn-github btn-round btn-lg"
            data-toggle="tooltip" data-original-title="Star on Github">
            <i class="fa fa-github"></i>
          </a>
        </div>
      </div>
      <hr>
      <div class="row align-items-center justify-content-md-between">
        <div class="col-md-6">
          <div class="copyright">
            &copy; 2018
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
          </div>
        </div>
        <div class="col-md-6">
          <!--
          <ul class="nav nav-footer justify-content-end">
            <li class="nav-item">
              <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
            </li>
            <li class="nav-item">
              <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
            </li>
            <li class="nav-item">
              <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
              <a href="https://github.com/creativetimofficial/argon-design-system/blob/master/LICENSE.md" class="nav-link"
                target="_blank">MIT License</a>
            </li>
            -->
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Core -->
  <script src="{% static '/assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/assets/vendor/popper/popper.min.js' %}"></script>
  <script src="{% static '/assets/vendor/bootstrap/bootstrap.min.js' %}"></script>
  <script src="{% static '/assets/vendor/headroom/headroom.min.js' %}"></script>
  <!-- Argon JS -->
  <script src="{% static '/assets/js/argon.js' %}%"></script>
</body>

</html>

connexus/accounts/templates/home.html
<h1>HOME</h1>
{% if user.is_authenticated %}
<p>{{ user.get_username }}</p>
<a href="{% url 'accounts:logout' %}">logout</a>
{% else %}
<a href="{% url 'accounts:login' %}">login</a>
{% endif %}

connexus/accounts/templates/login.html
<h1>REGISTER</h1>
<form method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

connexus/accounts/templates/register.html
<h1>REGISTER</h1>
<form method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>